### ISSUE TITLE
Permission denied issue caused by the wrong output path

### ISSUE THREAD

**Issue by randywang123** [amittai/cynical#8]
There is a path join issue that would cause a permission denied in line 155 of the python wrapper. 
https://github.com/amittai/cynical/blob/658e254b5db315024da0a9dc6c12b92b04e72f36/python_cynical_wrapper.py#L155

This line would make the final output path `/jaded.output` instead of `outdir/jaded.output`.

A simple quick fix is to remove the `/` like the following line. 

```python 
jaded_file = os.path.join(outdir, "jaded.output")
```

**Comment by Ssloto** [comment]
Thanks for raising this. It's definitely a typo on my end. I made the suggested change.
